In [132]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

In [133]:
df = pd.read_csv("../data/processed_data.csv")
df.head()

,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,Gate location,...,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,satisfaction,Total_Delay,Delayed_Flight,Average_Service_Rating,Long_Haul
0,Male,Loyal Customer,13,Personal Travel,Eco Plus,460,3,4,3,1,...,4,5,5,25,18.0,0,43.0,1,3.846154,0
1,Male,disloyal Customer,25,Business travel,Business,235,3,2,3,3,...,1,4,1,1,6.0,0,7.0,0,2.307692,0
2,Female,Loyal Customer,26,Business travel,Business,1142,2,2,2,2,...,4,4,5,0,0.0,1,0.0,0,3.846154,0
3,Female,Loyal Customer,25,Business travel,Business,562,2,5,5,5,...,1,4,2,11,9.0,0,20.0,1,2.846154,0
4,Male,Loyal Customer,61,Business travel,Business,214,3,3,3,3,...,3,3,3,0,0.0,1,0.0,0,3.538462,0

In [134]:
# Check the shape of the data
print(f"The data has {df.shape[0]} rows and {df.shape[1]} columns.")

The data has 103904 rows and 27 columns.

In [135]:
# Identify numerical and categorical columns
numerical_features = df.select_dtypes(include=['int64','float64']).columns
categorical_features = df.select_dtypes(include=['object', 'str']).columns

print(f"The data has {len(numerical_features)} numerical columns: {numerical_features.tolist()}")
print(f"The data has {len(categorical_features)} categorical columns: {categorical_features.tolist()}")

The data has 23 numerical columns: ['Age', 'Flight Distance', 'Inflight wifi service', 'Departure/Arrival time convenient', 'Ease of Online booking', 'Gate location', 'Food and drink', 'Online boarding', 'Seat comfort', 'Inflight entertainment', 'On-board service', 'Leg room service', 'Baggage handling', 'Checkin service', 'Inflight service', 'Cleanliness', 'Departure Delay in Minutes', 'Arrival Delay in Minutes', 'satisfaction', 'Total_Delay', 'Delayed_Flight', 'Average_Service_Rating', 'Long_Haul']
The data has 4 categorical columns: ['Gender', 'Customer Type', 'Type of Travel', 'Class']

In [136]:
# Identify discrete & continuous columns
discrete_columns = [
    column for column in numerical_features if df[column].nunique() <= 10
]
continuous_columns = [
    column for column in numerical_features if column not in discrete_columns
]

print(f"The data has {len(discrete_columns)} discrete columns: {discrete_columns}")
print(f"The data has {len(continuous_columns)} continuous columns: {continuous_columns}")

The data has 17 discrete columns: ['Inflight wifi service', 'Departure/Arrival time convenient', 'Ease of Online booking', 'Gate location', 'Food and drink', 'Online boarding', 'Seat comfort', 'Inflight entertainment', 'On-board service', 'Leg room service', 'Baggage handling', 'Checkin service', 'Inflight service', 'Cleanliness', 'satisfaction', 'Delayed_Flight', 'Long_Haul']
The data has 6 continuous columns: ['Age', 'Flight Distance', 'Departure Delay in Minutes', 'Arrival Delay in Minutes', 'Total_Delay', 'Average_Service_Rating']

## Checking for skewness

In [137]:
df[continuous_columns].skew()

Age                          -0.004516
Flight Distance               1.109466
Departure Delay in Minutes    6.733980
Arrival Delay in Minutes      6.605288
Total_Delay                   6.787318
Average_Service_Rating       -0.105862
dtype: float64

* skewness > zero -> Right Skewed
* skewness = negative -> Left Skewed

## Splitting features

In [138]:
df['Age'].describe()

count    103904.000000
mean         39.379706
std          15.114964
min           7.000000
25%          27.000000
50%          40.000000
75%          51.000000
max          85.000000
Name: Age, dtype: float64

In [139]:
skewed_columns = ['Flight Distance', 'Departure Delay in Minutes', 'Arrival Delay in Minutes', 'Total_Delay']

scaling_columns = ['Age', 'Average_Service_Rating']

discrete_features = [
    'Inflight wifi service', 'Departure/Arrival time convenient', 
    'Ease of Online booking', 'Gate location', 'Food and drink', 
    'Online boarding', 'Seat comfort', 'Inflight entertainment', 
    'On-board service', 'Leg room service', 'Baggage handling', 
    'Checkin service', 'Inflight service', 'Cleanliness', 
    'Delayed_Flight', 'Long_Haul'
]

categorical_columns = ['Gender', 'Customer Type', 'Type of Travel', 'Class']

In [140]:
final_features = skewed_columns + scaling_columns + discrete_features + categorical_columns
print(len(final_features))

26

**Train Test Split**

In [141]:
X = df[final_features]
y = df["satisfaction"]

In [142]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

print("Train Shape:", X_train.shape)
print("Test Shape:", X_test.shape)

Train Shape: (83123, 26)
Test Shape: (20781, 26)

## Preprocessing Pipeline

In [143]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import FunctionTransformer, StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer

# For skewed features
skew_pipeline = Pipeline(steps=[
    ('log_transform', FunctionTransformer(np.log1p)),
    ('scale', StandardScaler())
])

# For numeric Features
scaling_pipeline = Pipeline(steps=[
    ('scale',StandardScaler())
])

# For categorical features
categorical_pipeline = Pipeline(steps=[
    ('encode', OneHotEncoder(handle_unknown="ignore"))
])


preprocessor = ColumnTransformer(transformers=[
    ("skewness", skew_pipeline, skewed_columns),
    ("scaler", scaling_pipeline, scaling_columns),
    ("category", categorical_pipeline, categorical_columns),
    ("discrete", "passthrough", discrete_features),
])

preprocessor

ColumnTransformer(transformers=[('skewness',
                                 Pipeline(steps=[('log_transform',
                                                  FunctionTransformer(func=<ufunc 'log1p'>)),
                                                 ('scale', StandardScaler())]),
                                 ['Flight Distance',
                                  'Departure Delay in Minutes',
                                  'Arrival Delay in Minutes', 'Total_Delay']),
                                ('scaler',
                                 Pipeline(steps=[('scale', StandardScaler())]),
                                 ['Age', 'Average_Service_Rating']),
                                ('category',
                                 Pipeline(steps=[(...
                                 ['Gender', 'Customer Type', 'Type of Travel',
                                  'Class']),
                                ('discrete', 'passthrough',
                                 ['Inflight wifi service',
                                  'Departure/Arrival time convenient',
                                  'Ease of Online booking', 'Gate location',
                                  'Food and drink', 'Online boarding',
                                  'Seat comfort', 'Inflight entertainment',
                                  'On-board service', 'Leg room service',
                                  'Baggage handling', 'Checkin service',
                                  'Inflight service', 'Cleanliness',
                                  'Delayed_Flight', 'Long_Haul'])])

In [144]:
X_train_processed = preprocessor.fit_transform(X_train)
X_test_processed = preprocessor.transform(X_test)

In [145]:
print("Preprocessed X_train shape:", X_train_processed.shape)
print("Preprocessed X_test shape:", X_test_processed.shape)

Preprocessed X_train shape: (83123, 31)
Preprocessed X_test shape: (20781, 31)

## Baseline Model Training

In [146]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, classification_report

In [147]:
models = { 
    "Logistic Regression": LogisticRegression(max_iter=1000, random_state=42), 
    "KNN": KNeighborsClassifier(), 
    "Decision Tree": DecisionTreeClassifier(random_state=42), 
    "Random Forest": RandomForestClassifier(random_state=42), 
    "XGBoost": XGBClassifier(random_state=42) 
}

In [148]:
trained_models = {}
for name, model in models.items():
    model.fit(X_train_processed, y_train)
    trained_models[name] = model

predictions = {}
for name, model in trained_models.items():
    predictions[name] = model.predict(X_test_processed)

results = []
for name, y_pred in predictions.items():
    results.append({
        "Model": name,
        "Accuracy": accuracy_score(y_test, y_pred),
        "Precision": precision_score(y_test, y_pred),
        "Recall": recall_score(y_test, y_pred),
        "F1-Score": f1_score(y_test, y_pred),
        "ROC-AUC": roc_auc_score(y_test, y_pred)
    })

results_df = pd.DataFrame(results)
results_df = results_df.sort_values(by="Accuracy", ascending=False).reset_index(drop=True)
results_df.round(3)

                 Model  Accuracy  Precision  Recall  F1-Score  ROC-AUC
0              XGBoost     0.964      0.967   0.949     0.958    0.962
1        Random Forest     0.962      0.968   0.944     0.956    0.960
2        Decision Tree     0.944      0.929   0.942     0.936    0.944
3                  KNN     0.928      0.938   0.894     0.915    0.924
4  Logistic Regression     0.877      0.869   0.843     0.856    0.873

Well, i evaluated five baseline classification models and XGBoost performed best with a F1-Score of 95.8% & Random Forest with a F1-Score of 95.6%. So, i selected XGBoost and Random Forest as the baseline champion and will now optimize all model with their  hyperparameters to improve prediction performance.

## Hyperparameter Optimization

**Tuned XGBoost**

In [149]:
from sklearn.model_selection import RandomizedSearchCV
xgb_pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('classifier', XGBClassifier(random_state=42))
])

xgb_params = {
    'classifier__n_estimators'  : [100, 150, 200, 300, 400],
    'classifier__max_depth'     : [3, 5, 7, 9, 12],
    'classifier__learning_rate' : [0.01, 0.05, 0.1, 0.2, 0.5],
    'classifier__subsample'     : [0.7, 0.85, 1.0],
}

tuned_xgb = RandomizedSearchCV(
    estimator=xgb_pipeline,
    param_distributions=xgb_params,
    n_iter=20,
    cv=5,
    scoring='accuracy',
    random_state=42,
    n_jobs=1,
    verbose=1
)

tuned_xgb.fit(X_train, y_train)

Fitting 5 folds for each of 20 candidates, totalling 100 fits

RandomizedSearchCV(cv=5,
                   estimator=Pipeline(steps=[('preprocessor',
                                              ColumnTransformer(transformers=[('skewness',
                                                                               Pipeline(steps=[('log_transform',
                                                                                                FunctionTransformer(func=<ufunc 'log1p'>)),
                                                                                               ('scale',
                                                                                                StandardScaler())]),
                                                                               ['Flight '
                                                                                'Distance',
                                                                                'Departure '
                                                                                'Delay '
                                                                                'in '
                                                                                'Minutes',
                                                                                'Arrival '
                                                                                'Delay '
                                                                                'in '
                                                                                'Minutes',
                                                                                'Total_Delay']),
                                                                              ('scaler',
                                                                               Pipeline(steps=[('scale',
                                                                                                Sta...
                                                            monotone_constraints=None,
                                                            multi_strategy=None,
                                                            n_estimators=None,
                                                            n_jobs=None,
                                                            num_parallel_tree=None, ...))]),
                   n_iter=20, n_jobs=1,
                   param_distributions={'classifier__learning_rate': [0.01,
                                                                      0.05, 0.1,
                                                                      0.2,
                                                                      0.5],
                                        'classifier__max_depth': [3, 5, 7, 9,
                                                                  12],
                                        'classifier__n_estimators': [100, 150,
                                                                     200, 300,
                                                                     400],
                                        'classifier__subsample': [0.7, 0.85,
                                                                  1.0]},
                   random_state=42, scoring='accuracy', verbose=1)

In [150]:
print(tuned_xgb.best_params_)
print("Accuracy score of tuned xgb:", tuned_xgb.best_score_)

{'classifier__subsample': 0.7, 'classifier__n_estimators': 200, 'classifier__max_depth': 9, 'classifier__learning_rate': 0.05}
Accuracy score of tuned xgb: 0.9633675352963739

**Tuned Random Forest**

In [151]:
rf_pipeline = Pipeline([
    ('preprocessor', preprocessor), 
    ('classifier', RandomForestClassifier(random_state=42))
])

rf_params = {
    'classifier__n_estimators'      : [50, 100, 150, 200],
    'classifier__max_depth'         : [1, 2, 3, 5],
    'classifier__min_samples_split' : [2, 3, 5, 8],
    'classifier__min_samples_leaf'  : [1, 2, 4, 6],
}

tuned_rf = RandomizedSearchCV(
    estimator=rf_pipeline,
    param_distributions=rf_params,
    n_iter=20,
    cv=5,
    scoring='accuracy',
    random_state=42,
    n_jobs=-1,     
    verbose=3
)

tuned_rf.fit(X_train, y_train)

Fitting 5 folds for each of 20 candidates, totalling 100 fits

RandomizedSearchCV(cv=5,
                   estimator=Pipeline(steps=[('preprocessor',
                                              ColumnTransformer(transformers=[('skewness',
                                                                               Pipeline(steps=[('log_transform',
                                                                                                FunctionTransformer(func=<ufunc 'log1p'>)),
                                                                                               ('scale',
                                                                                                StandardScaler())]),
                                                                               ['Flight '
                                                                                'Distance',
                                                                                'Departure '
                                                                                'Delay '
                                                                                'in '
                                                                                'Minutes',
                                                                                'Arrival '
                                                                                'Delay '
                                                                                'in '
                                                                                'Minutes',
                                                                                'Total_Delay']),
                                                                              ('scaler',
                                                                               Pipeline(steps=[('scale',
                                                                                                Sta...
                                                                                'Cleanliness',
                                                                                'Delayed_Flight',
                                                                                'Long_Haul'])])),
                                             ('classifier',
                                              RandomForestClassifier(random_state=42))]),
                   n_iter=20, n_jobs=-1,
                   param_distributions={'classifier__max_depth': [1, 2, 3, 5],
                                        'classifier__min_samples_leaf': [1, 2,
                                                                         4, 6],
                                        'classifier__min_samples_split': [2, 3,
                                                                          5,
                                                                          8],
                                        'classifier__n_estimators': [50, 100,
                                                                     150,
                                                                     200]},
                   random_state=42, scoring='accuracy', verbose=3)

In [152]:
print(tuned_rf.best_params_)
print("Accuracy score of tuned random forest:", tuned_rf.best_score_)

{'classifier__n_estimators': 200, 'classifier__min_samples_split': 3, 'classifier__min_samples_leaf': 1, 'classifier__max_depth': 5}
Accuracy score of tuned random forest: 0.9185544494055158

**Tuned Decision Tree**

In [153]:
dt_pipeline = Pipeline([
    ('preprocessor', preprocessor), 
    ('classifier', DecisionTreeClassifier(random_state=42))
])

dt_params = {
    'classifier__max_depth'         : [1, 2, 3, 5, 7, 10, None],
    'classifier__min_samples_split' : [2, 3, 5, 8, 10],
    'classifier__min_samples_leaf'  : [1, 2, 4, 6],
    'classifier__criterion'         : ['gini', 'entropy', 'log_loss'],
}

tuned_dt = RandomizedSearchCV(
    estimator=dt_pipeline,
    param_distributions=dt_params,
    n_iter=20,
    cv=5,
    scoring='accuracy',
    random_state=42,
    n_jobs=-1,
    verbose=3
)

tuned_dt.fit(X_train, y_train)

Fitting 5 folds for each of 20 candidates, totalling 100 fits

RandomizedSearchCV(cv=5,
                   estimator=Pipeline(steps=[('preprocessor',
                                              ColumnTransformer(transformers=[('skewness',
                                                                               Pipeline(steps=[('log_transform',
                                                                                                FunctionTransformer(func=<ufunc 'log1p'>)),
                                                                                               ('scale',
                                                                                                StandardScaler())]),
                                                                               ['Flight '
                                                                                'Distance',
                                                                                'Departure '
                                                                                'Delay '
                                                                                'in '
                                                                                'Minutes',
                                                                                'Arrival '
                                                                                'Delay '
                                                                                'in '
                                                                                'Minutes',
                                                                                'Total_Delay']),
                                                                              ('scaler',
                                                                               Pipeline(steps=[('scale',
                                                                                                Sta...
                                                                                'Delayed_Flight',
                                                                                'Long_Haul'])])),
                                             ('classifier',
                                              DecisionTreeClassifier(random_state=42))]),
                   n_iter=20, n_jobs=-1,
                   param_distributions={'classifier__criterion': ['gini',
                                                                  'entropy',
                                                                  'log_loss'],
                                        'classifier__max_depth': [1, 2, 3, 5, 7,
                                                                  10, None],
                                        'classifier__min_samples_leaf': [1, 2,
                                                                         4, 6],
                                        'classifier__min_samples_split': [2, 3,
                                                                          5, 8,
                                                                          10]},
                   random_state=42, scoring='accuracy', verbose=3)

In [154]:
print(tuned_dt.best_params_)
print("Accuracy score of tuned decision tree:", tuned_dt.best_score_)

{'classifier__min_samples_split': 5, 'classifier__min_samples_leaf': 6, 'classifier__max_depth': None, 'classifier__criterion': 'gini'}
Accuracy score of tuned decision tree: 0.9485942925166622

**Tuned KNN**

In [155]:
knn_pipeline = Pipeline([
    ('preprocessor', preprocessor), 
    ('classifier', KNeighborsClassifier())
])

knn_params = {
    'classifier__n_neighbors' : [3, 5, 7, 9, 11, 15, 21],
    'classifier__weights'     : ['uniform', 'distance'],
    'classifier__metric'      : ['euclidean', 'manhattan'],
}

tuned_knn = RandomizedSearchCV(
    estimator=knn_pipeline,
    param_distributions=knn_params,
    n_iter=20,
    cv=5,
    scoring='accuracy',
    random_state=42,
    n_jobs=-1,
    verbose=3
)

tuned_knn.fit(X_train, y_train)

Fitting 5 folds for each of 20 candidates, totalling 100 fits

RandomizedSearchCV(cv=5,
                   estimator=Pipeline(steps=[('preprocessor',
                                              ColumnTransformer(transformers=[('skewness',
                                                                               Pipeline(steps=[('log_transform',
                                                                                                FunctionTransformer(func=<ufunc 'log1p'>)),
                                                                                               ('scale',
                                                                                                StandardScaler())]),
                                                                               ['Flight '
                                                                                'Distance',
                                                                                'Departure '
                                                                                'Delay '
                                                                                'in '
                                                                                'Minutes',
                                                                                'Arrival '
                                                                                'Delay '
                                                                                'in '
                                                                                'Minutes',
                                                                                'Total_Delay']),
                                                                              ('scaler',
                                                                               Pipeline(steps=[('scale',
                                                                                                Sta...
                                                                                'Checkin '
                                                                                'service',
                                                                                'Inflight '
                                                                                'service',
                                                                                'Cleanliness',
                                                                                'Delayed_Flight',
                                                                                'Long_Haul'])])),
                                             ('classifier',
                                              KNeighborsClassifier())]),
                   n_iter=20, n_jobs=-1,
                   param_distributions={'classifier__metric': ['euclidean',
                                                               'manhattan'],
                                        'classifier__n_neighbors': [3, 5, 7, 9,
                                                                    11, 15,
                                                                    21],
                                        'classifier__weights': ['uniform',
                                                                'distance']},
                   random_state=42, scoring='accuracy', verbose=3)

In [156]:
print(tuned_knn.best_params_)
print("Accuracy score of tuned knn:", tuned_knn.best_score_)

{'classifier__weights': 'distance', 'classifier__n_neighbors': 15, 'classifier__metric': 'manhattan'}
Accuracy score of tuned knn: 0.934229987625464

**Tuned Logistic Regression**

In [157]:
lr_pipeline = Pipeline([
    ('preprocessor', preprocessor), 
    ('classifier', LogisticRegression(random_state=42, max_iter=1000))
])

lr_params = {
    'classifier__C'       : [0.001, 0.01, 0.1, 1, 10, 100],
    'classifier__penalty' : ['l1', 'l2'],
    'classifier__solver'  : ['liblinear', 'saga'],
}

tuned_lr = RandomizedSearchCV(
    estimator=lr_pipeline,
    param_distributions=lr_params,
    n_iter=20,
    cv=5,
    scoring='accuracy',
    random_state=42,
    n_jobs=-1,
    verbose=3
)

tuned_lr.fit(X_train, y_train)

Fitting 5 folds for each of 20 candidates, totalling 100 fits

RandomizedSearchCV(cv=5,
                   estimator=Pipeline(steps=[('preprocessor',
                                              ColumnTransformer(transformers=[('skewness',
                                                                               Pipeline(steps=[('log_transform',
                                                                                                FunctionTransformer(func=<ufunc 'log1p'>)),
                                                                                               ('scale',
                                                                                                StandardScaler())]),
                                                                               ['Flight '
                                                                                'Distance',
                                                                                'Departure '
                                                                                'Delay '
                                                                                'in '
                                                                                'Minutes',
                                                                                'Arrival '
                                                                                'Delay '
                                                                                'in '
                                                                                'Minutes',
                                                                                'Total_Delay']),
                                                                              ('scaler',
                                                                               Pipeline(steps=[('scale',
                                                                                                Sta...
                                                                                'service',
                                                                                'Inflight '
                                                                                'service',
                                                                                'Cleanliness',
                                                                                'Delayed_Flight',
                                                                                'Long_Haul'])])),
                                             ('classifier',
                                              LogisticRegression(max_iter=1000,
                                                                 random_state=42))]),
                   n_iter=20, n_jobs=-1,
                   param_distributions={'classifier__C': [0.001, 0.01, 0.1, 1,
                                                          10, 100],
                                        'classifier__penalty': ['l1', 'l2'],
                                        'classifier__solver': ['liblinear',
                                                               'saga']},
                   random_state=42, scoring='accuracy', verbose=3)

In [158]:
print(tuned_lr.best_params_)
print("Accuracy score of tuned lr:", tuned_lr.best_score_)

{'classifier__solver': 'liblinear', 'classifier__penalty': 'l1', 'classifier__C': 0.1}
Accuracy score of tuned lr: 0.8756421436169827

**Final comparison of tuned models**

In [159]:
tuned_results = pd.DataFrame({

    'Model': [
        'Logistic Regression',
        'KNN',
        'Decision Tree',
        'Random Forest',
        'XGBoost'
    ],

    'F1 Score': [
        f1_score(y_test, tuned_lr.predict(X_test)),
        f1_score(y_test, tuned_knn.predict(X_test)),
        f1_score(y_test, tuned_dt.predict(X_test)),
        f1_score(y_test, tuned_rf.predict(X_test)),
        f1_score(y_test, tuned_xgb.predict(X_test))
    ]

})

tuned_results.sort_values(by='F1 Score', ascending=False)

                 Model  F1 Score
4              XGBoost  0.957670
2        Decision Tree  0.940232
1                  KNN  0.923792
3        Random Forest  0.905558
0  Logistic Regression  0.855790

In [160]:
from sklearn.metrics import classification_report, confusion_matrix
y_pred = tuned_xgb.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[11510   266]
 [  487  8518]]
              precision    recall  f1-score   support

           0       0.96      0.98      0.97     11776
           1       0.97      0.95      0.96      9005

    accuracy                           0.96     20781
   macro avg       0.96      0.96      0.96     20781
weighted avg       0.96      0.96      0.96     20781

In [161]:
from sklearn.metrics import roc_auc_score

y_prob = tuned_xgb.predict_proba(X_test)[:, 1]
auc = roc_auc_score(y_test, y_prob)

print("ROC-AUC Score:", auc)

ROC-AUC Score: 0.9954285945459045

In [162]:
import joblib
joblib.dump(tuned_xgb, "../model/passenger_satisfaction_model.pkl")

['../model/passenger_satisfaction_model.pkl']

After preprocessing the dataset and training multiple machine learning models, hyperparameter optimization was performed using RandomSearchCV. The evaluated models included Logistic Regression, K-Nearest Neighbors, Decision Tree, Random Forest and XGBoost. Among all models, XGBoost achieved the best performance with an F1 Score of 95% and an accuracy of 96%. The model also obtained a ROC-AUC score of 99%, demonstrating excellent class-separation capability. Based on these evaluation metrics, XGBoost was selected as the final model for prediction and deployment.